{{- range $name, $job := .Values.jobs }}
{{- if include "should_be_deployed" (list $ .) }}
{{- $secrets :=  include "imagePullSecrets" (list $ .imagePullSecrets ) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
    app: {{ $name }}
    role: {{ .role | default "job" }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
  {{- end }}
  backoffLimit: {{ .backoffLimit | default "0" }}
  {{- if .completions }}
  completions: {{ .completions }}
  {{- end }}
  {{- if .parallelism }}
  parallelism: {{ .parallelism }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "helm.labels" $ | nindent 8 }}
        app: {{ $name }}
        role: {{ .role | default "job" }}
        {{- with .labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ $name }}
          imagePullPolicy: {{ .imagePullPolicy | default "Always" }}
          image: {{ tpl .image $ }}
          {{- with .command }}
          command: {{ toJson . }}
          {{- end }}
          {{- with .args }}
          args: {{ toJson . }}
          {{- end }}
          {{- if or .env .env_by_tier .env_by_br .env_tpl }}
          env:
            {{- if .env }}
            {{- include "env_tpl" (list $ .env) | nindent 12 }}
            {{- end }}
            {{- include "env_by_pluck" (list $.Values.global.tier .env_by_tier) | nindent 12 }}
            {{- include "env_by_pluck" (list $.Values.global.git_branch .env_by_br) | nindent 12 }}
            {{- if .env_tpl }}
            {{- tpl .env_tpl $ | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .volumeMounts }}
          volumeMounts: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .envFrom }}
          envFrom: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- include "pod_resources" (set $.Values.global "_app" $name) | nindent 10 }}
      {{- $secrets | nindent 6}}
      restartPolicy: {{ .restartPolicy | default "Never" }}
      {{- with .hostAliases }}
      hostAliases: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if hasKey . "serviceAccount" }}
      {{- if hasKey .serviceAccount "name" }}
      serviceAccountName: {{ .serviceAccount.name }}
      {{- else }}
      serviceAccountName: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if .pool }}
      {{- if $pool_name:= pluck $.Values.global.tier .pool | first }}
      nodeSelector:
        pool: {{ $pool_name }}
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: {{ $pool_name }}
          effect: "NoSchedule"
      {{- end }}
      {{- end }}
      {{- with .volumes }}
      volumes: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
